// @ts-expect-error generated by OpenNext during build
import handler from "./.open-next/worker.js";
import { processDuePushNotifications } from "./lib/server/push-delivery";
import { ensureAutomaticReminders } from "./lib/server/automatic-reminders";

type ScheduledContext = {
  waitUntil(promise: Promise<unknown>): void;
};

const worker = {
  fetch: handler.fetch,
  scheduled(_controller: unknown, env: CloudflareEnv, ctx: ScheduledContext) {
    ctx.waitUntil(
      ensureAutomaticReminders(env)
        .then((result) => console.info("automatic-reminders", result))
        .then(() => processDuePushNotifications(env))
        .then((result) => console.info("push-delivery", result))
        .catch((error) => {
          console.error("push-delivery-failed", error);
          throw error;
        }),
    );
  },
};

export default worker;

// @ts-expect-error generated by OpenNext during build
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
