// @ts-ignore generated by OpenNext during build
import handler from "./.open-next/worker.js";
import { processDuePushNotifications } from "./lib/server/push-delivery";

export default {
  fetch: handler.fetch,
  async scheduled(_controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    ctx.waitUntil(processDuePushNotifications(env));
  },
} satisfies ExportedHandler<CloudflareEnv>;

// @ts-ignore generated by OpenNext during build
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
